### ISSUE TITLE
PyQt5: module 'sys' has no attribute '_MEIPASS'

### ISSUE THREAD

**Issue by thijstriemstra** [python-babel/babel#525]
I'm using Babel 2.5.0 with a PyQt5 application (and Python 3.6.2)

Since #505 is merged Babel broke with this error:

```
[   65.699014] photobooth1 photobooth[544]: File "bootstrap.py", line 961, in _find_and_load
[   65.699698] photobooth1 photobooth[544]: File "bootstrap.py", line 950, in _find_and_load_unlocked
[   65.701137] photobooth1 photobooth[544]: File "bootstrap.py", line 646, in _load_unlocked
[   65.702115] photobooth1 photobooth[544]: File "bootstrap.py", line 616, in _load_backward_compatible
[   65.703041] photobooth1 photobooth[544]: File ":/babel/__init__.py", line 20, in <module>
[   65.703965] photobooth1 photobooth[544]: File "bootstrap.py", line 961, in _find_and_load
[   65.704915] photobooth1 photobooth[544]: File "bootstrap.py", line 950, in _find_and_load_unlocked
[   65.705829] photobooth1 photobooth[544]: File "bootstrap.py", line 646, in _load_unlocked
[   65.706741] photobooth1 photobooth[544]: File "bootstrap.py", line 616, in _load_backward_compatible
[   65.707675] photobooth1 photobooth[544]: File ":/babel/core.py", line 14, in <module>
[   65.708605] photobooth1 photobooth[544]: File "bootstrap.py", line 1009, in _handle_fromlist
[   65.709501] photobooth1 photobooth[544]: File "bootstrap.py", line 205, in _call_with_frames_removed
[   65.710438] photobooth1 photobooth[544]: File "bootstrap.py", line 961, in _find_and_load
[   65.711376] photobooth1 photobooth[544]: File "bootstrap.py", line 950, in _find_and_load_unlocked
[   65.712256] photobooth1 photobooth[544]: File "bootstrap.py", line 646, in _load_unlocked
[   65.713217] photobooth1 photobooth[544]: File "bootstrap.py", line 616, in _load_backward_compatible
[   65.714132] photobooth1 photobooth[544]: File ":/babel/localedata.py", line 35, in <module>
[   65.715039] photobooth1 photobooth[544]: File ":/babel/localedata.py", line 27, in get_base_dir
[   65.715972] photobooth1 photobooth[544]: AttributeError: module 'sys' has no attribute '_MEIPASS'
```

This is caused by PyInstaller support introduced with #505. But PyQt5 does not have a `_MEIPASS` attribute, hence:

```
AttributeError: module 'sys' has no attribute '_MEIPASS'
```

Downgrading to 2.4.0 resolved it again (obviously).

**Comment by akx** [comment]
Yet it has a truthy `sys.frozen`? 😮

**Comment by akx** [comment]
This has been fixed in [v2.5.1](https://github.com/python-babel/babel/releases/tag/v2.5.1).

Thanks for the bug report!

**Comment by thijstriemstra** [comment]
Thanks!
